name: Build and Run TaskManager Application
on:
  push:
    paths:
      - '**/*.java'
  pull_request:
    paths:
      - '**/*.java'
  workflow_dispatch: # Enables manual trigger
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven Tests
        run: mvn -f pom.xml test

  build-and-run:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -f pom.xml clean package -DskipTests

      - name: Run Spring Boot Application
        run: |
          java -jar target/*.jar &
          echo $! > springboot.pid
        timeout-minutes: 5

      - name: Shutdown Spring Boot Application
        run: kill $(cat springboot.pid)
